
import { jsPDF } from 'jspdf';
import { Order } from '../types';

/**
 * Generates a high-fidelity, black-and-white logistics manifest PDF locally.
 * This ensures the app remains functional even if the Supabase Edge Function is unreachable.
 */
export const generateLocalPDFBase64 = async (order: Order): Promise<string> => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const address = order.shippingAddress || order.shipping_address;
  const isCOD = order.payment_mode === 'Cash on Delivery';
  const subtotal = order.total / 1.18;
  const gst = order.total - subtotal;

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text('VEXOKART LOGISTICS', 20, 20);
  
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('AUTHORIZED DIGITAL FULFILLMENT NODE • V.5.0', 20, 25);

  // Payment Type Badge
  doc.setFillColor(0, 0, 0);
  doc.rect(150, 12, 40, 12, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(isCOD ? 'COD' : 'PREPAID', 170, 20, { align: 'center' });

  // Order ID
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.text(`MANIFEST #${order.id}`, 190, 28, { align: 'right' });

  // Divider
  doc.setLineWidth(0.5);
  doc.line(20, 32, 190, 32);

  // Address Grid
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('SOLD BY (SELLER NODE)', 20, 40);
  doc.text('SHIP TO (CONSIGNEE)', 110, 40);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(order.seller_name || 'VexoKart Official Store', 20, 46);
  doc.text(address?.fullName || 'Verified Buyer', 110, 46);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(['Fulfillment Node-A1', 'VexoKart Logistics Park', 'Ph: 1800-VEXO-KART'], 20, 52);
  
  const customerAddr = [
    address?.street || '',
    `${address?.city || ''}, ${address?.state || ''}`,
    `PIN: ${address?.zip || ''}`,
    `Phone: ${address?.phone || ''}`
  ];
  doc.text(customerAddr, 110, 52);

  // Middle Divider
  doc.line(20, 75, 190, 75);

  // Tracking Visuals Placeholder
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.rect(20, 80, 120, 20);
  doc.text('INTERNAL_BARCODE_NODE_ID_' + order.id, 80, 92, { align: 'center' });
  
  doc.rect(155, 80, 25, 25);
  doc.text('QR_NODE', 167.5, 94, { align: 'center' });

  // Item Table
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('ITEM MANIFEST DESCRIPTION', 20, 115);
  doc.text('QTY', 150, 115, { align: 'center' });
  doc.text('PRICE', 180, 115, { align: 'right' });
  doc.line(20, 117, 190, 117);

  doc.setFont('helvetica', 'normal');
  let y = 125;
  order.items.forEach((item) => {
    doc.text(item.name.substring(0, 50), 20, y);
    doc.text(String(item.quantity), 150, y, { align: 'center' });
    doc.text(`INR ${item.price.toLocaleString()}`, 180, y, { align: 'right' });
    y += 8;
  });

  // Totals
  doc.line(130, y + 5, 190, y + 5);
  y += 12;
  doc.setFontSize(8);
  doc.text('SUBTOTAL', 130, y);
  doc.text(`INR ${subtotal.toFixed(2)}`, 180, y, { align: 'right' });
  
  y += 6;
  doc.text('GST (18%)', 130, y);
  doc.text(`INR ${gst.toFixed(2)}`, 180, y, { align: 'right' });

  y += 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('TOTAL PAYABLE', 130, y);
  doc.text(`INR ${order.total.toLocaleString()}`, 180, y, { align: 'right' });

  // Footer
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('ELECTRONIC CONSIGNMENT NOTE • GENERATED BY VEXOKART PROTOCOL V.5.0', 105, 280, { align: 'center' });

  const pdfOutput = doc.output('blob');
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = (reader.result as string).split(',')[1];
      resolve(base64String);
    };
    reader.readAsDataURL(pdfOutput);
  });
};
